import { trpc } from "@/lib/trpc";
import { ArrowUpRight, FileClock, RefreshCw } from "lucide-react";
import { Link } from "wouter";
import { DataSourceNote, EmptyData, PageIntro, StatusBadge } from "@/components/solarvision/Primitives";

export default function History() {
  const { data, isLoading, refetch } = trpc.inspection.history.useQuery({ limit: 100 });
  const rows = data ?? [];
  return <div><PageIntro eyebrow="Traceability" title="Inspection history." description="Every completed run is listed here with its source file, detection count, measured latency, and persistence state." action={<button onClick={() => refetch()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-600 transition-colors hover:border-slate-300 hover:text-slate-900"><RefreshCw className="h-4 w-4" />Refresh</button>} /><DataSourceNote configured={rows.length > 0} /><div className="rounded-2xl border border-slate-200/80 bg-white shadow-[0_10px_30px_rgba(7,27,41,0.04)]"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#FFF3C4] text-[#F2B941]"><FileClock className="h-4 w-4" /></div><div><h2 className="text-base font-semibold">All inspection runs</h2><p className="text-xs text-slate-400">{rows.length} records returned</p></div></div><Link href="/inspection" className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#F2B941]">New inspection <ArrowUpRight className="h-3.5 w-3.5" /></Link></div>{isLoading ? <div className="p-8 text-sm text-slate-400">Loading stored inspections…</div> : rows.length > 0 ? <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-[10px] uppercase tracking-[0.16em] text-slate-400"><th className="px-6 py-4 font-semibold">Source image</th><th className="py-4 font-semibold">Status</th><th className="py-4 font-semibold">Detections</th><th className="py-4 font-semibold">Latency</th><th className="py-4 font-semibold">Persistence</th><th className="py-4 pr-6 font-semibold">Created</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(item => <tr key={item.inspectionId} className="transition-colors hover:bg-[#f8fafb]"><td className="px-6 py-4"><p className="font-semibold text-slate-700">{item.sourceFilename}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{item.inspectionId.slice(0, 12)}</p></td><td className="py-4"><StatusBadge tone={item.status === "completed" ? "success" : "danger"}>{item.status}</StatusBadge></td><td className="py-4 font-medium text-slate-600">{item.detectionsCount}</td><td className="py-4 font-mono text-slate-500">{Math.round(item.processingTimeMs)} ms</td><td className="max-w-[180px] truncate py-4 text-[11px] text-slate-400" title={item.persistenceStatus}>{item.persistenceStatus}</td><td className="py-4 pr-6 text-[11px] text-slate-400">{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="p-6"><EmptyData title="No inspection records" description="Run an inspection once the model runtime is available. Stored results will appear here without sample rows." /></div>}</div></div>;
}
