import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Clock3, Database, Gauge, ScanLine, Sparkles, Target, UploadCloud } from "lucide-react";
import { Link } from "wouter";
import { DataSourceNote, EmptyData, PageIntro, StatusBadge } from "@/components/solarvision/Primitives";

function StatCard({ label, value, detail, icon: Icon, accent }: { label: string; value: string | number; detail: string; icon: typeof Target; accent: string }) {
  return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_10px_30px_rgba(7,27,41,0.04)]"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-[-0.05em] text-[#071b29]">{value}</p><p className="mt-1 text-[11px] text-slate-400">{detail}</p></div><div className="grid h-10 w-10 place-items-center rounded-xl" style={{ backgroundColor: `${accent}15`, color: accent }}><Icon className="h-5 w-5" /></div></div></div>;
}

export default function Home() {
  const { data: stats, isLoading } = trpc.dashboard.stats.useQuery();
  const { data: model } = trpc.model.status.useQuery();
  const { data: history } = trpc.inspection.history.useQuery({ limit: 4 });
  const configured = Boolean(stats?.configured);
  const modelReady = model?.exists;

  return <div>
    <PageIntro eyebrow="Operations overview" title="See the line clearly." description="A single workspace for EL/NIR inspection, defect evidence, and the next layer of smart-manufacturing intelligence." action={<Link href="/inspection" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#071b29] px-4 py-3 text-sm font-semibold text-white shadow-[0_8px_20px_rgba(7,27,41,0.14)] transition-transform hover:-translate-y-0.5"><ScanLine className="h-4 w-4 text-[#0bd3b0]" />Run inspection<ArrowRight className="h-4 w-4" /></Link>} />
    <DataSourceNote configured={configured} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Inspections processed" value={isLoading ? "…" : configured ? stats?.inspections ?? 0 : 0} detail="Stored inspection records" icon={ScanLine} accent="#0bd3b0" />
      <StatCard label="Defects detected" value={isLoading ? "…" : configured ? stats?.detections ?? 0 : 0} detail="Across persisted detections" icon={Target} accent="#e3a336" />
      <StatCard label="Defect classes seen" value={isLoading ? "…" : configured ? stats?.defectTypes ?? 0 : 0} detail="Unique labels in the database" icon={Gauge} accent="#7a7ff5" />
      <StatCard label="Average processing" value={configured && stats?.avgProcessingTimeMs != null ? `${Math.round(stats.avgProcessingTimeMs)} ms` : "—"} detail="Measured model latency" icon={Clock3} accent="#db6c91" />
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_0.65fr]">
      <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_10px_30px_rgba(7,27,41,0.04)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#079a86]">First-minute workflow</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.03em]">From cell image to evidence</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">Upload an EL/NIR frame to run the configured YOLO26n checkpoint. The result includes real bounding boxes, confidence scores, and an annotated image.</p></div><div className="hidden h-12 w-12 place-items-center rounded-2xl bg-[#e8fbf7] text-[#079a86] sm:grid"><Sparkles className="h-5 w-5" /></div></div><div className="mt-7 grid gap-3 sm:grid-cols-4">{[{n:"01", label:"Upload", icon:UploadCloud}, {n:"02", label:"Infer", icon:Sparkles}, {n:"03", label:"Review", icon:Target}, {n:"04", label:"Persist", icon:Database}].map(step => <div key={step.n} className="relative rounded-xl bg-[#f6f9fa] p-4"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-slate-400">{step.n}</span><step.icon className="h-4 w-4 text-[#0bd3b0]" /></div><p className="mt-5 text-sm font-semibold text-slate-700">{step.label}</p></div>)}</div></div>
      <div className="rounded-2xl bg-[#071b29] p-6 text-white shadow-[0_12px_32px_rgba(7,27,41,0.15)]"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#0bd3b0]">Runtime status</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.03em]">Inspection engine</h2></div><StatusBadge tone={modelReady ? "success" : "warning"}>{modelReady ? "Checkpoint present" : "Setup required"}</StatusBadge></div><div className="mt-7 space-y-4">{[{label:"YOLO26n checkpoint", value:modelReady ? "best.pt detected" : "best.pt not found", ok:modelReady}, {label:"Database persistence", value:configured ? "Connected" : "Integration pending", ok:configured}, {label:"Sensor root-cause layer", value:"M2 extension point", ok:false}].map(item => <div key={item.label} className="flex items-center justify-between gap-3 border-b border-white/10 pb-3"><div className="flex items-center gap-2.5"><span className={item.ok ? "text-[#0bd3b0]" : "text-slate-500"}>{item.ok ? <CheckCircle2 className="h-4 w-4" /> : <span className="block h-1.5 w-1.5 rounded-full bg-slate-500" />}</span><span className="text-xs text-slate-300">{item.label}</span></div><span className="text-right text-[11px] text-slate-500">{item.value}</span></div>)}</div><Link href="/model" className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-[#0bd3b0] hover:text-white">View model status <ArrowRight className="h-3.5 w-3.5" /></Link></div>
    </div>
    <div className="mt-5 rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_10px_30px_rgba(7,27,41,0.04)]"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#079a86]">Latest activity</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.03em]">Inspection history</h2></div><Link href="/history" className="text-xs font-semibold text-[#079a86] hover:text-[#071b29]">View all <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></div>{history && history.length > 0 ? <div className="divide-y divide-slate-100">{history.map(item => <div key={item.inspectionId} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-700">{item.sourceFilename}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{item.inspectionId.slice(0, 8)} · {new Date(item.createdAt).toLocaleString()}</p></div><div className="flex items-center gap-5"><span className="text-xs text-slate-500">{item.detectionsCount} detections</span><span className="font-mono text-xs text-slate-500">{Math.round(item.processingTimeMs)} ms</span><StatusBadge tone={item.status === "completed" ? "success" : "danger"}>{item.status}</StatusBadge></div></div>)}</div> : <EmptyData compact title="No inspections yet" description="Run the first inspection to populate this activity feed from the database." />}</div>
  </div>;
}
