import { ArrowRight, Bot, BrainCircuit, Cable, CheckCircle2, Cpu, DatabaseZap, Wrench } from "lucide-react";
import { PageIntro, StatusBadge } from "@/components/solarvision/Primitives";

const phases = [
  { id: "M1", title: "Vision inspection", status: "Implemented", tone: "success" as const, icon: Bot, copy: "EL/NIR image upload, YOLO26n inference, bounding boxes, confidence scores, annotated evidence, history, and defect analytics." },
  { id: "M2", title: "Root-cause analysis", status: "Extension point", tone: "warning" as const, icon: BrainCircuit, copy: "Join inspection defects with machine sensor windows. Train Random Forest or XGBoost models only after labeled sensor events and verified causal features exist." },
  { id: "M3", title: "Predictive maintenance", status: "Extension point", tone: "warning" as const, icon: Wrench, copy: "Add machine health features, failure horizons, maintenance actions, and operator feedback loops. Predictions must be backed by a validated model and timestamped sensor data." },
  { id: "M4", title: "Connected factory", status: "Extension point", tone: "neutral" as const, icon: Cable, copy: "Connect MES/SCADA/PLC systems, alerts, role-based workflows, and production-level quality controls with explicit lineage for every decision." },
];

export default function Roadmap() {
  return <div><PageIntro eyebrow="Product architecture" title="The next layers are ready." description="SolarVision is modular by design. M1 is the evidence loop; later modules attach to its stable inspection and detection records instead of creating parallel data silos." /><div className="relative space-y-4">{phases.map((phase, index) => <div key={phase.id} className="relative grid gap-5 rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_10px_30px_rgba(7,27,41,0.04)] md:grid-cols-[110px_1fr_auto] md:items-center"><div className="flex items-center gap-4 md:block"><div className="inline-flex items-center gap-2 rounded-full bg-[#F4F0D7] px-3 py-1.5 font-mono text-xs font-medium text-slate-500"><span className="text-[#F2B941]">{phase.id}</span><span className="text-slate-300">/</span><span>0{index + 1}</span></div><phase.icon className="hidden h-9 w-9 text-slate-200 md:mt-5 md:block" /></div><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-semibold tracking-[-0.03em]">{phase.title}</h2><StatusBadge tone={phase.tone}>{phase.status}</StatusBadge></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{phase.copy}</p></div><div className="flex items-center gap-2 text-xs text-slate-400"><CheckCircle2 className={phase.id === "M1" ? "h-4 w-4 text-[#F2B941]" : "h-4 w-4 text-slate-300"} />{phase.id === "M1" ? "Current scope" : "Integration pending"}</div></div>)}</div><div className="mt-5 rounded-2xl bg-[#0B0909] p-6 text-white"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#F2B941]">Stable contract</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.03em]">Inspection → Detection → Context</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Future services can subscribe to the inspection ID, detection label, confidence, bounding box, and timestamp without changing the operator workflow.</p></div><div className="flex shrink-0 items-center gap-2 font-mono text-xs text-[#F2B941]"><DatabaseZap className="h-4 w-4" />ready for M2 <ArrowRight className="h-4 w-4" /></div></div></div></div>;
}
