import { trpc } from "@/lib/trpc";
import { Database, Gauge, HardDrive, ImageIcon, Save, Server, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { PageIntro, StatusBadge } from "@/components/solarvision/Primitives";

const DEFAULTS = { confidence: 0.25, imageSize: 640, maxUploadMb: 20 };

export default function Settings() {
  const { data: model } = trpc.model.status.useQuery();
  const [values, setValues] = useState(DEFAULTS);
  useEffect(() => {
    const saved = localStorage.getItem("solarvision-settings");
    if (saved) {
      try { setValues({ ...DEFAULTS, ...JSON.parse(saved) }); } catch { /* reset to safe defaults */ }
    }
  }, []);
  const save = () => { localStorage.setItem("solarvision-settings", JSON.stringify(values)); window.dispatchEvent(new CustomEvent("solarvision:settings-changed", { detail: values })); toast.success("Inspection settings saved for this operator"); };
  const supabaseReady = Boolean(model?.supabaseConfigured);
  return <div><PageIntro eyebrow="Control plane" title="Settings." description="Tune operator-side inspection preferences without exposing model or Supabase secrets in the browser." action={<button onClick={save} className="flex items-center gap-2 rounded-xl bg-[#0B0909] px-4 py-2.5 text-xs font-semibold text-white transition-transform hover:-translate-y-0.5 active:scale-95"><Save className="h-4 w-4 text-[#F2B941]" />Save settings</button>} />
    <div className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
      <section className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_10px_30px_rgba(7,27,41,0.04)]"><div className="mb-6 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#FFF3C4] text-[#0B0909]"><Gauge className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#F2B941]">Inspection</p><h2 className="mt-1 text-xl font-semibold">Runtime preferences</h2></div></div><div className="space-y-6"><label className="block"><span className="text-sm font-semibold text-slate-700">Default confidence threshold</span><span className="mt-1 block text-xs text-slate-400">Used by the backend model configuration. Lower values surface more candidate detections.</span><div className="mt-3 flex items-center gap-4"><input type="range" min="0.05" max="0.95" step="0.05" value={values.confidence} onChange={event => setValues(current => ({ ...current, confidence: Number(event.target.value) }))} className="w-full accent-[#F2B941]" /><span className="w-14 rounded-lg bg-[#F4F0D7] px-2 py-2 text-center font-mono text-xs font-semibold">{values.confidence.toFixed(2)}</span></div></label><label className="block"><span className="text-sm font-semibold text-slate-700">Inference image size</span><span className="mt-1 block text-xs text-slate-400">Displayed for operator reference. Server-side changes require deployment configuration.</span><select value={values.imageSize} onChange={event => setValues(current => ({ ...current, imageSize: Number(event.target.value) }))} className="mt-3 w-full rounded-xl border border-slate-200 bg-[#F4F0D7] px-3 py-3 text-sm outline-none focus:border-[#F2B941]"><option value={640}>640 × 640</option><option value={960}>960 × 960</option><option value={1280}>1280 × 1280</option></select></label><label className="block"><span className="text-sm font-semibold text-slate-700">Maximum upload size</span><span className="mt-1 block text-xs text-slate-400">Client-side guardrail for EL/NIR image uploads.</span><select value={values.maxUploadMb} onChange={event => setValues(current => ({ ...current, maxUploadMb: Number(event.target.value) }))} className="mt-3 w-full rounded-xl border border-slate-200 bg-[#F4F0D7] px-3 py-3 text-sm outline-none focus:border-[#F2B941]"><option value={10}>10 MB</option><option value={20}>20 MB</option><option value={50}>50 MB</option></select></label></div></section>
      <section className="space-y-5"><div className="rounded-2xl bg-[#0B0909] p-6 text-white"><div className="flex items-center gap-3"><Server className="h-5 w-5 text-[#F2B941]" /><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#F2B941]">System</p><h2 className="mt-1 text-xl font-semibold">Runtime status</h2></div></div><div className="mt-6 space-y-4"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="h-4 w-4" />YOLO checkpoint</span><StatusBadge tone={model?.exists ? "success" : "danger"}>{model?.exists ? "Present" : "Missing"}</StatusBadge></div><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="flex items-center gap-2 text-xs text-slate-400"><Database className="h-4 w-4" />Supabase adapter</span><StatusBadge tone={supabaseReady ? "success" : "warning"}>{supabaseReady ? "Connected" : "Pending"}</StatusBadge></div><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-slate-400"><HardDrive className="h-4 w-4" />Local fallback</span><StatusBadge tone="success">Available</StatusBadge></div></div></div><div className="rounded-2xl border border-slate-200/80 bg-white p-6"><div className="flex items-center gap-3"><ImageIcon className="h-5 w-5 text-[#F2B941]" /><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#F2B941]">Safety note</p><h2 className="mt-1 text-base font-semibold">EL/NIR images only</h2></div></div><p className="mt-4 text-xs leading-5 text-slate-500">This model is trained for electroluminescence or near-infrared inspection imagery. Ordinary RGB panel photographs can produce misleading detections and should not be used as production evidence.</p></div></section>
    </div></div>;
}
